### ISSUE TITLE
Incompatible with Lua 5.2.0

### ISSUE THREAD

**Issue by ghost** [brimworks/lua-yajl#10]
When compiling against Lua 5.2.0, getfenv, setfenv, and objlen are missing. Lua 5.2 uses lexical scopes instead of dynamic ones. objlen could be changed to rawlen, but since I haven't looked closely at what you are manipulating the environment for I don't have a patch. I may offer one up shortly.

**Comment by brimworks** [comment]
Patches are always welcomed :).

Thanks,
-Brian

**Comment by hp77-creator** [comment]
Hi @brimworks how can one ensure that it will compile for both versions i.e 5.1 & > 5.1 
I am new to Lua, how is it handled in Lua ecosystem? any suggestions, I am open to sending the patch

**Comment by brimworks** [comment]
Unfortunately, some of the API breaking changes require rethinking how this library works when porting to 5.2.

[Like this one](https://www.lua.org/manual/5.2/manual.html#8.3):
* Pseudoindex LUA_ENVIRONINDEX and functions lua_getfenv/lua_setfenv were removed, as C functions no longer have environments.

This change looks like it would be easy to work around with a preprocessor compiler directive though:
* Function lua_objlen was renamed [lua_rawlen](https://www.lua.org/manual/5.2/manual.html#lua_rawlen).

**Comment by brimworks** [comment]
Actually, the fix was easier than expected. @hp77-creator do you mind checking out my branch and verifying it works for you? Here is the PR:

https://github.com/brimworks/lua-yajl/pull/18

**Comment by brimworks** [comment]
PR was merged, so this should be fixed. I'll plan to do a lua rocks release soon.

**Comment by hp77-creator** [comment]
Hi @brimworks thanks for swift response, I was afk for sometime due to vacation, will check. Thanks a lot.
