### ISSUE TITLE
MIT Licence implies a "boilerplate" header is needed, at least at top of lua_yajl.c

### ISSUE THREAD

**Issue by SlySven** [brimworks/lua-yajl#11]
We ([Mudlet](https://github.com/mudlet/mudlet.git)) are using `lua-yajl.c` within our project but the `README.md` here says (and some other files suggest) that you have licensed this under the terms of the MIT licence, which explicitly states:

    ...
    * The above copyright notice and this permission notice shall be included in
    * all copies or substantial portions of the Software.
    ...

therefore for us to compile with the licence terms: "...shall be included in all copies or substantial portions of the Software..." there __MUST__ be a copy of the licence text within that file... 👼 

Can you fix this? You might want to update the copyright to include the years that have seen modifications by yourself and the two other contributors which look to me as it can be summarised (when you do so) as:

    Copyright (c) 2009-2012, 2017 Brian Maher
    Copyright (c) 2011 Alexander Gladysh
    Copyright (c) 2011 Dave Reisner

By the way, the GitHub [licensing a repository](https://help.github.com/articles/licensing-a-repository/) link can enable you to display an item on the "Code" tab that indicates the repository licence for ease use for others considering your project... 😀

**Comment by brimworks** [comment]
Good suggestion, I incorporated this in a PR out for adding 5.2+ Lua support.

**Comment by brimworks** [comment]
Done
