### ISSUE TITLE
Serializing an array with functions generates nonsense

### ISSUE THREAD

**Issue by smurfix** [brimworks/lua-yajl#13]
This is a problem.

```
> py.action
{
  call = "function: 0x55d2c69c10c0",
  init = "function: 0x55d2c36eda10",
  handle = "function: 0x55d2c366da50",
  set = "function: 0x55d2c6989f10",
  unhandle = "function: 0x55d2c6a51c20",
  get = "function: 0x55d2c69e2780"
}
> yajl.to_string(py.action)
"{"call":"init","handle":"set","unhandle":"get"}"
```
> py.action.foo="bar"
> yajl.to_string(py.action)
"{"call":"foo","bar":"init","handle":"set","unhandle":"get"}

**Comment by brimworks** [comment]
Thanks for the bug report, sorry for the delay in processing this. I do intend to address this bug, although I wonder what the "right" behavior is (obviously the current behavior is completely wrong).

I'm thinking right now that I'll use `lua_tolstring` to stringify any key or value that would not conform to the standard JSON types. In other words, if it isn't a table, string, number, or boolean, we would use `lua_tolstring` to try to have a sensible value. The alternative is that I could just omit these... but it would be better to use the `__gen_json` metatable to explicitly handle these types in my opinion, and using `lua_tolstring` output may be handy when debugging, so this seems like a reasonable default.

Thoughts?

**Comment by brimworks** [comment]
...actually, I just realize that we are already coercing the key using the global function `tostring`, so I'll follow that same pattern for the value.

**Comment by brimworks** [comment]
Pending PR: https://github.com/brimworks/lua-yajl/pull/20

If I don't hear anything by next weekend, then I'll merge it.
