### ISSUE TITLE
Memory leak in js_to_value

### ISSUE THREAD

**Issue by kyzentun** [brimworks/lua-yajl#15]
If one of the js_parser_assert conditions fails, the parser handle is leaked.  This can be tested by adding an invalid json string to the test script.

```
            handle = <span class="pl-c1">yajl_alloc</span>(&amp;js_to_value_callbacks, <span class="pl-c1">NULL</span>, (<span class="pl-k">void</span>*)L);
```

This handle needs to be encapsulated in a userdata, the way the handle js_parser is, with a gc function so it is freed when the object is garbage collected.

**Comment by brimworks** [comment]
PR posted: https://github.com/brimworks/lua-yajl/pull/19

If I don't hear anything in a week, then I'll merge it.

**Comment by brimworks** [comment]
Merged. This should be fixed now.
